=== HenrikTrom/multi-camera-calib/cfg/CameraCalibrationSettings.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "CameraCalibrationSettings",
    "type": "object",
    "properties": {
        "pattern_size_first": {
            "type": "integer"
        },
        "pattern_size_second": {
            "type": "integer"
        },
        "charuco_params_border_size": {
            "type": "number"
        },
        "charuco_params_dict": {
            "type": "integer"
        },
        "charuco_params_marker_border_pixel": {
            "type": "integer"
        },
        "charuco_params_marker_to_square_ratio": {
            "type": "number"
        },
        "charuco_params_square_size": {
            "type": "number"
        },
        "serial_numbers": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "main_cam_serial": {
            "type": "string"
        },
        "savedir": {
            "type": "string"
        }
    },
    "required": [
        "pattern_size_first",
        "pattern_size_second",
        "charuco_params_border_size",
        "charuco_params_dict",
        "charuco_params_marker_border_pixel",
        "charuco_params_marker_to_square_ratio",
        "charuco_params_square_size",
        "serial_numbers",
        "main_cam_serial",
        "savedir"
    ]
}

=== HenrikTrom/multi-camera-calib/cfg/CameraCalibrationSettings.json
{
    "pattern_size_first": 11,
    "pattern_size_second": 7,
    "charuco_params_border_size": 1.0,
    "charuco_params_dict": 0,
    "charuco_params_marker_border_pixel": 1,
    "charuco_params_marker_to_square_ratio": 0.75,
    "charuco_params_square_size": 80.0,
    "serial_numbers": [
        "19037266",
        "19246521",
        "20174578",
        "19338645",
        "19421325"
    ],
    "main_cam_serial": "19037266",
    "savedir": "/home/docker/workspace/workspace/src/flir_icp_calib/cfg"
}
